source 'https://rubygems.org'

gem "sinatra"

gem "sinatra-contrib"

gem "sinatra-erb"

gem "sass"

gem "mail"

gem "dm-timestamps"

gem "dm-validations"

gem "dm-core"

gem "dm-migrations"

gem "thin"

gem "sinatra-flash"

group :production do
	gem "pg"
	gem "dm-postgres-adapter"
end

group :development, :test do
	gem "sqlite3"
	gem "dm-sqlite-adapter"
end
