CREATE VIEW MOVIE_ACTOR_VIEW AS
SELECT MAL.MID, M.YEAR, P.Name, P.PID
FROM MOVIE M, Person P, MOVIE_ACTOR_LIST MAL
WHERE M.MID = MAL.MID
AND P.PID = MAL.ACTOR;

CREATE VIEW LONGEVITY_VIEW AS
SELECT MAX(YEAR) - MIN(YEAR) AS LONGEVITY, PID FROM MOVIE_ACTOR_VIEW
GROUP BY PID;

SELECT NAME
FROM PERSON
WHERE PID IN (
SELECT PID FROM LONGEVITY_VIEW
WHERE LONGEVITY = (SELECT MAX(LONGEVITY) FROM LONGEVITY_VIEW));