CREATE VIEW HIGH_RATED_MOVIES_VIEW AS
SELECT MOVIE, COUNT(RATING) AS NUM_RATING, AVG(RATING) AS RATING
FROM REVIEWS
GROUP BY MOVIE
HAVING AVG(RATING) = (SELECT MAX(AVG(RATING)) FROM REVIEWS GROUP BY MOVIE);

SELECT M.MID, M.NAME, M.YEAR, V.RATING, V.NUM_RATING
FROM MOVIE M, HIGH_RATED_MOVIES_VIEW V
WHERE M.MID = V.MOVIE;