CREATE VIEW CAST_SIZE_VIEW AS
SELECT MOVIE, COUNT(DISTINCT(PERSON)) AS CAST_SIZE
FROM ROLES 
GROUP BY MOVIE
HAVING COUNT(DISTINCT(PERSON)) = (SELECT MAX(COUNT(DISTINCT(PERSON))) FROM ROLES GROUP BY MOVIE)

SELECT M.NAME, V.CAST_SIZE
FROM MOVIE M, CAST_SIZE_VIEW V
WHERE M.MID = V.MOVIE;