CREATE VIEW MAX_ROLE_VIEW AS
SELECT R.PERSON AS PID, M.NAME AS MNAME, P.NAME
FROM MOVIE M, PERSON P, ROLES R
WHERE M.MID = R.MOVIE 
AND P.PID = R.PERSON
AND M.YEAR = 2010;

SELECT MNAME, NAME, COUNT(NAME) AS NUM_ROLES
FROM MAX_ROLE_VIEW
GROUP BY MNAME, NAME
HAVING COUNT(NAME) = (SELECT MAX(COUNT(NAME)) AS NUM_ROLES FROM MAX_ROLE_VIEW GROUP BY MNAME, NAME);
