CREATE VIEW TOP_RATED_ACTORS AS
SELECT NAME 
FROM PERSON
WHERE PID IN
(SELECT ACTOR FROM MOVIE_ACTOR_LIST WHERE MID IN (SELECT MOVIE FROM REVIEWS GROUP BY MOVIE HAVING AVG(RATING) >= 8 ));

CREATE VIEW LOW_RATED_ACTORS AS
SELECT NAME 
FROM PERSON
WHERE PID IN
(SELECT ACTOR FROM MOVIE_ACTOR_LIST WHERE MID IN (SELECT MOVIE FROM REVIEWS GROUP BY MOVIE HAVING AVG(RATING) < 8 ));

SELECT COUNT(*) FROM TOP_RATED_ACTORS A WHERE A.NAME NOT IN(SELECT * FROM LOW_RATED_ACTORS);

CREATE VIEW FINAL_TOP_ACTOR_LIST AS SELECT * FROM TOP_RATED_ACTORS A WHERE A.NAME NOT IN(SELECT A2.NAME FROM LOW_RATED_ACTORS A2);

CREATE VIEW MOVIE_COUNT AS
SELECT ACTOR, COUNT(*) AS MOVIE_COUNT FROM MOVIE_ACTOR_LIST WHERE ACTOR IN (SELECT PID FROM FINAL_TOP_ACTOR_LIST GROUP BY PID) GROUP BY ACTOR;

SELECT * FROM (SELECT * 
FROM MOVIE_COUNT MC,  FINAL_TOP_ACTOR_LIST TAL
WHERE MC.ACTOR = TAL.PID
ORDER BY MC.MOVIE_COUNT DESC, NAME) WHERE ROWNUM <= 10;
